version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - tests

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "go", "test", "-v", "data" ]
